# CHUG Configuration - Local Development

# PostgreSQL connection URL (local Docker)
pg_url: "postgresql://chugger:secret@localhost:5433/chugdb"

# ClickHouse connection URL (local Docker)
ch_url: "http://localhost:9000"

# --- Single Table Mode ---
# Uncomment to ingest a single table
# table: "users"
# limit: 1000          # Max rows (0 = unlimited)
# batch_size: 500      # Rows per batch
# polling:
#   enabled: false
#   delta_column: "updated_at"
#   interval_seconds: 30

# --- Multi-Table Mode (Recommended) ---
# Comment out 'table' above and use 'tables' below for multiple tables

# Global defaults (apply to all tables unless overridden)
limit: 0
batch_size: 500

tables:
  # Simple table (uses global defaults)
  - name: "users"

  # Table with custom batch size
  - name: "orders"
    batch_size: 1000

  # Table with polling enabled
  - name: "events"
    polling:
      enabled: true
      delta_column: "updated_at"
      interval_seconds: 60

  # Table with custom limit
  - name: "products"
    limit: 10000
